### ISSUE TITLE
CI: upgrade SwiftLint to 0.24.0 (or newer) version

### ISSUE THREAD

**Issue by r-mckay** [twittemb/Weavy#11]
Hi Thibault,

I'm sorry for this "kinda" duplicated issue (of #8) but it seems that the CI uses the "0.22.0" version of SwiftLint. 
However, with the 0.24.0 version, the project does not compile and triggers warnings.

Maybe that the CI could use this last version.

Thank you sir!

**Comment by twittemb** [comment]
Hi @r-mckay 
I've upgraded Swiftlint on my laptop and we get rid of all the bad stuff. The CI will be ok because there is a fresh new install of Swiftlint each time.

**Comment by r-mckay** [comment]
Hi @twittemb 

I don't think it is each time a fresh install. For instance, we can read in the CI execution:

```
$ brew install swiftlint || true
Error: swiftlint 0.22.0 is already installed
To upgrade to 0.24.0, run `brew upgrade swiftlint`
```

Here is an example for a previous PR for Weavy: https://travis-ci.org/twittemb/Weavy/jobs/305590008
