### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by svoip** [twittemb/Weavy#7]
This library seems neat. 
Will there be a Cocoapods support?

**Comment by twittemb** [comment]
Hi.
Thanks for the feedback. I'm currently adding CocoaPods support. 
Should be OK in the next hours/days.
Thanks.

**Comment by twittemb** [comment]
@rsardek Hi. Weavy is now available in CocoaPods (as well as Carthage): https://cocoapods.org/pods/Weavy

See the README for the installation instructions.

Thanks.

And feel free to give me some feedback.
