### ISSUE TITLE
SwiftLint 'superfluous_disable_command' error.

### ISSUE THREAD

**Issue by r-mckay** [twittemb/Weavy#8]
Hi Thibault!

I have the following SwiftLint error while compiling:
Loom.swift:12:45: error: Superfluous Disable Command Violation: SwiftLint rule 'class_delegate_protocol' did not trigger a violation in the disabled region. Please remove the disable command. (superfluous_disable_command)

It may be related to the SwiftLint version I'm using (0.24.0).
I'll submit a PR in a few moments.

Thanks!

**Comment by twittemb** [comment]
Hi @r-mckay 
this is related to my local version of Swiftlint. See me comment on the dedicated PR.
I close this issue as it is no longer relevant as soon as the PR will be merged.
Thanks.
